version: "3.9"
services:
  api:
    build:
      context: ./server
    ports:
      - "8080:80"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
    volumes:
      - ./server:/app
    restart: unless-stopped
